INSERT INTO abilities (name) VALUES('Adaptability');
INSERT INTO abilities (name) VALUES('Aftermath');
INSERT INTO abilities (name) VALUES('Air Lock');
INSERT INTO abilities (name) VALUES('Anger Point');
INSERT INTO abilities (name) VALUES('Anticipation');
INSERT INTO abilities (name) VALUES('Arena Trap');
INSERT INTO abilities (name) VALUES('Aura Break');
INSERT INTO abilities (name) VALUES('Bad Dreams');
INSERT INTO abilities (name) VALUES('Battle Armor');
INSERT INTO abilities (name) VALUES('Big Pecks');
INSERT INTO abilities (name) VALUES('Blaze');
INSERT INTO abilities (name) VALUES('Cheek Pouch');
INSERT INTO abilities (name) VALUES('Chlorophyll');
INSERT INTO abilities (name) VALUES('Clear Body');
INSERT INTO abilities (name) VALUES('Cloud Nine');
INSERT INTO abilities (name) VALUES('Color Change');
INSERT INTO abilities (name) VALUES('Competitive');
INSERT INTO abilities (name) VALUES('Compound Eyes');
INSERT INTO abilities (name) VALUES('Contrary');
INSERT INTO abilities (name) VALUES('Cursed Body');
INSERT INTO abilities (name) VALUES('Cute Charm');
INSERT INTO abilities (name) VALUES('Damp');
INSERT INTO abilities (name) VALUES('Dark Aura');
INSERT INTO abilities (name) VALUES('Defeatist');
INSERT INTO abilities (name) VALUES('Defiant');
INSERT INTO abilities (name) VALUES('Download');
INSERT INTO abilities (name) VALUES('Drizzle');
INSERT INTO abilities (name) VALUES('Drought');
INSERT INTO abilities (name) VALUES('Dry Skin');
INSERT INTO abilities (name) VALUES('Early Bird');
INSERT INTO abilities (name) VALUES('Effect Spore');
INSERT INTO abilities (name) VALUES('Fairy Aura');
INSERT INTO abilities (name) VALUES('Filter');
INSERT INTO abilities (name) VALUES('Flame Body');
INSERT INTO abilities (name) VALUES('Flash Fire');
INSERT INTO abilities (name) VALUES('Flower Gift');
INSERT INTO abilities (name) VALUES('Flower Veil');
INSERT INTO abilities (name) VALUES('Forecast');
INSERT INTO abilities (name) VALUES('Forewarn');
INSERT INTO abilities (name) VALUES('Frisk');
INSERT INTO abilities (name) VALUES('Fur Coat');
INSERT INTO abilities (name) VALUES('Gluttony');
INSERT INTO abilities (name) VALUES('Guts');
INSERT INTO abilities (name) VALUES('Healer');
INSERT INTO abilities (name) VALUES('Heatproof');
INSERT INTO abilities (name) VALUES('Honey Gather');
INSERT INTO abilities (name) VALUES('Huge Power');
INSERT INTO abilities (name) VALUES('Hustle');
INSERT INTO abilities (name) VALUES('Hydration');
INSERT INTO abilities (name) VALUES('Hyper Cutter');
INSERT INTO abilities (name) VALUES('Ice Body');
INSERT INTO abilities (name) VALUES('Illuminate');
INSERT INTO abilities (name) VALUES('Illusion');
INSERT INTO abilities (name) VALUES('Immunity');
INSERT INTO abilities (name) VALUES('Infiltrator');
INSERT INTO abilities (name) VALUES('Inner Focus');
INSERT INTO abilities (name) VALUES('Insomnia');
INSERT INTO abilities (name) VALUES('Intimidate');
INSERT INTO abilities (name) VALUES('Iron Barbs');
INSERT INTO abilities (name) VALUES('Iron Fist');
INSERT INTO abilities (name) VALUES('Justified');
INSERT INTO abilities (name) VALUES('Keen Eye');
INSERT INTO abilities (name) VALUES('Klutz');
INSERT INTO abilities (name) VALUES('Leaf Guard');
INSERT INTO abilities (name) VALUES('Levitate');
INSERT INTO abilities (name) VALUES('Lightning Rod');
INSERT INTO abilities (name) VALUES('Limber');
INSERT INTO abilities (name) VALUES('Liquid Ooze');
INSERT INTO abilities (name) VALUES('Magic Guard');
INSERT INTO abilities (name) VALUES('Magician');
INSERT INTO abilities (name) VALUES('Magma Armor');
INSERT INTO abilities (name) VALUES('Magnet Pull');
INSERT INTO abilities (name) VALUES('Marvel Scale');
INSERT INTO abilities (name) VALUES('Mega Launcher');
INSERT INTO abilities (name) VALUES('Minus');
INSERT INTO abilities (name) VALUES('Mold Breaker');
INSERT INTO abilities (name) VALUES('Motor Drive');
INSERT INTO abilities (name) VALUES('Moxie');
INSERT INTO abilities (name) VALUES('Multitype');
INSERT INTO abilities (name) VALUES('Mummy');
INSERT INTO abilities (name) VALUES('Natural Cure');
INSERT INTO abilities (name) VALUES('No Guard');
INSERT INTO abilities (name) VALUES('Normalize');
INSERT INTO abilities (name) VALUES('Oblivious');
INSERT INTO abilities (name) VALUES('Overcoat');
INSERT INTO abilities (name) VALUES('Overgrow');
INSERT INTO abilities (name) VALUES('Own Tempo');
INSERT INTO abilities (name) VALUES('Pickup');
INSERT INTO abilities (name) VALUES('Plus');
INSERT INTO abilities (name) VALUES('Poison Heal');
INSERT INTO abilities (name) VALUES('Poison Point');
INSERT INTO abilities (name) VALUES('Poison Touch');
INSERT INTO abilities (name) VALUES('Prankster');
INSERT INTO abilities (name) VALUES('Pressure');
INSERT INTO abilities (name) VALUES('Pure Power');
INSERT INTO abilities (name) VALUES('Quick Feet');
INSERT INTO abilities (name) VALUES('Rain Dish');
INSERT INTO abilities (name) VALUES('Reckless');
INSERT INTO abilities (name) VALUES('Refrigerate');
INSERT INTO abilities (name) VALUES('Regenerator');
INSERT INTO abilities (name) VALUES('Rivalry');
INSERT INTO abilities (name) VALUES('Rock Head');
INSERT INTO abilities (name) VALUES('Rough Skin');
INSERT INTO abilities (name) VALUES('Run Away');
INSERT INTO abilities (name) VALUES('Sand Force');
INSERT INTO abilities (name) VALUES('Sand Rush');
INSERT INTO abilities (name) VALUES('Sand Stream');
INSERT INTO abilities (name) VALUES('Sand Veil');
INSERT INTO abilities (name) VALUES('Sap Sipper');
INSERT INTO abilities (name) VALUES('Scrappy');
INSERT INTO abilities (name) VALUES('Serene Grace');
INSERT INTO abilities (name) VALUES('Shadow Tag');
INSERT INTO abilities (name) VALUES('Shed Skin');
INSERT INTO abilities (name) VALUES('Sheer Force');
INSERT INTO abilities (name) VALUES('Shell Armor');
INSERT INTO abilities (name) VALUES('Shield Dust');
INSERT INTO abilities (name) VALUES('Simple');
INSERT INTO abilities (name) VALUES('Skill Link');
INSERT INTO abilities (name) VALUES('Slow Start');
INSERT INTO abilities (name) VALUES('Sniper');
INSERT INTO abilities (name) VALUES('Snow Cloak');
INSERT INTO abilities (name) VALUES('Snow Warning');
INSERT INTO abilities (name) VALUES('Solar Power');
INSERT INTO abilities (name) VALUES('Solid Rock');
INSERT INTO abilities (name) VALUES('Soundproof');
INSERT INTO abilities (name) VALUES('Speed Boost');
INSERT INTO abilities (name) VALUES('Stall');
INSERT INTO abilities (name) VALUES('Stance Change');
INSERT INTO abilities (name) VALUES('Static');
INSERT INTO abilities (name) VALUES('Steadfast');
INSERT INTO abilities (name) VALUES('Stench');
INSERT INTO abilities (name) VALUES('Sticky Hold');
INSERT INTO abilities (name) VALUES('Storm Drain');
INSERT INTO abilities (name) VALUES('Strong Jaw');
INSERT INTO abilities (name) VALUES('Sturdy');
INSERT INTO abilities (name) VALUES('Suction Cups');
INSERT INTO abilities (name) VALUES('Super Luck');
INSERT INTO abilities (name) VALUES('Swarm');
INSERT INTO abilities (name) VALUES('Sweet Veil');
INSERT INTO abilities (name) VALUES('Swift Swim');
INSERT INTO abilities (name) VALUES('Synchronize');
INSERT INTO abilities (name) VALUES('Tangled Feet');
INSERT INTO abilities (name) VALUES('Technician');
INSERT INTO abilities (name) VALUES('Telepathy');
INSERT INTO abilities (name) VALUES('Teravolt');
INSERT INTO abilities (name) VALUES('Thick Fat');
INSERT INTO abilities (name) VALUES('Tinted Lens');
INSERT INTO abilities (name) VALUES('Torrent');
INSERT INTO abilities (name) VALUES('Tough Claws');
INSERT INTO abilities (name) VALUES('Trace');
INSERT INTO abilities (name) VALUES('Truant');
INSERT INTO abilities (name) VALUES('Turboblaze');
INSERT INTO abilities (name) VALUES('Unaware');
INSERT INTO abilities (name) VALUES('Unburden');
INSERT INTO abilities (name) VALUES('Unnerve');
INSERT INTO abilities (name) VALUES('Victory Star');
INSERT INTO abilities (name) VALUES('Vital Spirit');
INSERT INTO abilities (name) VALUES('Volt Absorb');
INSERT INTO abilities (name) VALUES('Water Absorb');
INSERT INTO abilities (name) VALUES('Water Veil');
INSERT INTO abilities (name) VALUES('Weak Armor');
INSERT INTO abilities (name) VALUES('White Smoke');
INSERT INTO abilities (name) VALUES('Wonder Guard');
INSERT INTO abilities (name) VALUES('Wonder Skin');